project/urls.py
from django.contrib import admin
from django.template.context_processors import static
from django.urls import path, include

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('rocks.urls'), name='rocks'),
    path('sign', include('users.urls'), name='sign'),
    ] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rocks/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
app_name: str = 'rocks'
urlpatterns = [
    path('', MainView.as_view(), name='home'),
    path('create/', RockCreateView.as_view(), name='create'),
    path('update/<int:pk>', RockUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', RockDeleteView.as_view(), name='delete'),
    path('rock/<int:pk>', RockView.as_view(), name='rock'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# users/urls.py

from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    # path('', home, name="home"),
    # path("signup/", SignUp.as_view(), name="signup"),
    path("signup/", UserRegister, name="signup"),
    path('user_profile/<int:pk>/', ShowProfilePageView.as_view(), name='user_profile'),
    path('create_user_profile/', CreateProfilePageView.as_view(), name='create_user_profile'),
    path('update_user_profile/<int:pk>/', UpdateProfilePageView.as_view(), name='update_user_profile'),
]

rocks/models.py
from django.db import models
from users.models import Tourist

# Create your models here.
class MountainPass(models.Model):
    CATEGORY = {"зима": "winter", "весна": "spring", "лето": "summer", "осень": "autumn"}

    """ФСТР проведут модерацию для каждого нового объекта и поменяют поле status
    new;
    pending — если модератор взял в работу;
    accepted — модерация прошла успешно;
    rejected — модерация прошла, информация не принята."""

    STATUS = {"новый": "new", "в ожидании": "pending", "подтвержден": "accepted", "отклонен": "rejected"}

    def user_directory_path(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        return '{0}/{1}'.format(instance.tourist.last_name, filename)

    tourist = models.ForeignKey(Tourist, on_delete=models.CASCADE)
    beauty_title = models.CharField(max_length=100, default="пер. ")
    title = models.CharField(max_length=100)
    add_time = models.DateTimeField(auto_now_add=True)
    latitude = models.DecimalField(max_digits=6, decimal_places=4)
    longitude = models.DecimalField(max_digits=6, decimal_places=4)
    height = models.IntegerField()
    level = models.CharField(choices=CATEGORY, max_length=100)
    level_category = models.CharField(max_length=100)
    image = models.ImageField(upload_to=user_directory_path, blank=True)
    pass_status = models.CharField(choices=STATUS, max_length=50,  default="новый", help_text="Изменить статус после проверки")

    def __str__(self):
        return f"Перевал '{self.title}', Позиция: {self.latitude}N / {self.longitude}E, Высота: {self.height}м, Статус: {self.pass_status}"

rocks/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, BooleanField  # true-false поле

from .models import MountainPass


class RockCreateForm(ModelForm):
    check_box = BooleanField(label='Сохранить')

    class Meta:
        model = MountainPass
        fields = ['title', 'latitude', 'longitude', 'height', 'level',
                  'level_category', 'image']  # 'tourist'

class RockUpdateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('tourist')
        super().__init__(*args, **kwargs)

        if not self.user.is_superuser:
            self.fields.pop('pass_status')

    check_box = BooleanField(label='Сохранить')

    class Meta:
        model = MountainPass
        fields = ['title', 'latitude', 'longitude', 'height', 'level',
                  'level_category', 'image', 'pass_status']  # 'tourist'

rocks/views.py
import datetime
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView

from . import forms
from .forms import RockCreateForm, RockUpdateForm
from .models import MountainPass


# Create your views here.
class MainView(ListView):
    model = MountainPass
    ordering = '-add_time'
    template_name = 'rocks/main_view.html'
    context_object_name = 'rocks'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.datetime.now()
        context['rocks_quantity'] = len(MountainPass.objects.all())
        return context


class RockView(ListView):
    model = MountainPass
    template_name = 'rocks/rock.html'
    context_object_name = 'rock'
    ordering = '-add_time'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        _id = self.kwargs.get('pk')
        context['time_now'] = datetime.datetime.utcnow()
        context['rock'] = MountainPass.objects.get(id=_id)
        return context


class RockCreateView(PermissionRequiredMixin, CreateView):
    form_class = RockCreateForm
    model = MountainPass
    permission_required = ('rocks.add_mountainpass',
                           'rocks.change_mountainpass')
    context_object_name = 'rock'
    template_name = 'rocks/create.html'

    def form_valid(self, form):
        rock = form.save(commit=False)
        if self.request.method == 'POST':
            rock.tourist = self.request.user.tourist
            rock.RockForm = datetime.date.today()
            rock.save()
            return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.datetime.utcnow()
        return context

    success_url = reverse_lazy('rocks:home')


class RockUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = ('rocks.change_mountainpass')
    form_class = RockUpdateForm
    model = MountainPass
    context_object_name = 'rock'
    template_name = 'rocks/update.html'
    success_url = '/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'tourist': self.request.user})
        return kwargs

    # def test_func(self):
    #     rock = self.get_object()
    #     if self.request.user == rock.tourist:
    #         return True
    #     return False

    def form_valid(self, form):
        # form.instance.tourist = self.request.user.tourist
        return super().form_valid(form)

    # получить информацию об объекте, который мы собираемся редактировать
    def get_object(self, **kwargs):
        _id = self.kwargs.get('pk')
        return MountainPass.objects.get(pk=_id)


class RockDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = ('rocks.delete_mountainpass')
    template_name = 'rocks/delete.html'
    queryset = MountainPass.objects.all()
    context_object_name = 'rock'
    success_url = '/'

    def test_func(self):
        rock = self.get_object()
        if self.request.user == rock.tourist:
            return True
        return False

rocks/templates/rocks/create.html
{% extends 'index.html' %}
{% load static %}

{% block title %} Create a new pass {% endblock title %}

{% block text %}
<h1> Новый перевал от "{{ user.tourist }}"</h1>
{% endblock text %}

{% block content %}
<div class="features">

    <form method="POST" class="form-parent" enctype="multipart/form-data">
          {% csrf_token %}
        <div class="form-error"> {{ form.non_field_errors }} </div>

          {% for f in form %}
                <p label class="form-label" for={{ f.id_for_lablel }}>
                 {{f.label}}: </label> {{f}} </p>
                <div class="form-error">{{f.errors}}</div>
          {% endfor %}

    <input type="submit" value= "Сохранить">

    </form>
</div>
<br/>  <br/>
    <a href="{% url 'rocks:home' %}">
        <li><i class="fa-solid fa-house"></i> <<<< На главнаую</li>
    </a>
{% endblock content %}

rocks/templates/rocks/delete.html
{% extends 'index.html' %}
{% block title %} Delete chosen pass {% endblock title %}

{% block content %}

{% if user.id == rock.tourist.user_id or user.is_superuser%}

<div class="features">
    <h1> {{user.tourist}}, вы действительно хотите удалить этот перевал? </h1>

    <table>
        <div class="table">
            <tr align="left">
                <th> Автор:</th>
                <th> title:</th>
                <th> level:</th>
                <th> Дата публикации:</th>
                <th> Статус:</th>
            </tr>

            <tr>
                <td width="300">{{rock.tourist}}</td>
                <td width="300">{{rock.title}}</td>
                <td width="100">{{rock.level}}</td>
                <td width="200">{{rock.add_time}}</td>
                <td width="100">{{rock.pass_status}}</td>


            </tr>
        </div>
    </table>

    <br>

    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm">
        <input type="button" value="Cancel" onclick="history.back()"/>
    </form>
    <br/> <br/>

    {% else %}
    <h2 style='color:red'>{{user}}, вы не можете удалить перевал от {{rock.tourist}}, не являясь его автором или модератором</h2>
    <a href="{% url 'rocks:home' %}">
        <li><i class="fa-solid fa-house"></i> <<<< На главнаую</li>
    </a>
    {% endif %}

    {% endblock content %}
</div>
</div>

rocks/templates/rocks/main_view.html
{% extends 'index.html' %}


{% block text %} <b style="color:#ff0099; font-size:30px"> Список перевалов </b> {% endblock text %}

{% block content %}

<div class="features">
    <h1> Главная страница </h1>

    <h3>
        На сегодняшнее число, {{ time_now|date:'d M Y' }},
        всего перевалов: {{ rocks_quantity }},
        из них, на этой странице показано: {{rocks|length}}.
    </h3>

    <hr>
    {% if rocks %}
    <table>
        <thead>
        <tr align="left">
            <th> "Автор:"</th>
            <th> "Название:"</th>
            <th> "Добавлен:"</th>
            <th> "latitude:"</th>
            <th> "longitude:"</th>
            <th> "height:"</th>
            <th> "level:"</th>
            <th> "Категория:"</th>
            <th> "Статус:"</th>
            <th> "Изменить:"</th>
            <th> "Удалить:"</th>
        </tr>
        </thead>

        {% for item in rocks %}
        <tr align="left">
            <td width="300"><a href="{% url 'users:user_profile' item.tourist.user_id %}">{{ item.tourist }}</a>
            </td>
            <td width="200"><a href="{% url 'rocks:rock' item.id %}">{{item.beauty_title}} {{ item.title }}</a>
            <td width="200">{{item.add_time}}</td>
            <td align="center"; width="70">{{item.latitude}}</td>
            <td align="center"; width="70">{{item.longitude}}</td>
            <td  width="100">{{item.height}}</td>
            <td align="center"; width="70">{{item.level}}</td>
            <td align="center"; width="70">{{item.level_category}}</td>
            <td width="120">{{item.pass_status}}</td>
            {% if user.tourist %}
            {% if item.pass_status == "новый" %}
            <td width="100"><a href="{% url 'rocks:update' item.id %}"><u>&#128260; изменить</u></a></td>
            {% elif item.pass_status == "отклонен" %}
            <td bgcolor="red" width="100">  </td>
            {% endif %}
            {% if item.pass_status == "отклонен" or item.pass_status == "новый" %}
            <td width="100"><a href="{% url 'rocks:delete' item.id %}"><u> &#128683; удалить</u></a></td>
            {% endif %}
            {% endif %}
        </tr>
        {% endfor %}
        <h5> Вы можете просмотреть перевал подробнее, кликнув по нему </h5>

    </table>

    {% else %}
    <h2> "Сегодня без новостей" &#129335;</h2>
    <br>

    {% endif %}
    <br>
    {% if is_paginated %}

    {% if page_obj.has_previous %}
    <a href="?page=1">First</a>
    <a href="?page={{ page_obj.previous_page_number }}">&#9194;</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a>{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"> &#9193;</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
    {% endif %}
</div>

{% endblock %}

rocks/templates/rocks/rock.html
{% extends 'index.html' %}
{% block content %}
<!-- nav bar -->


<div class="container">
    <div class="card" style="max-width: 50rem;">
        <h2>
            <div class="card-header"> Зарегистрирован {{ rock.add_time }}</div>
            <br/>
            <div class="card-header">
               <h3>туристом:  <a href="{% url 'users:user_profile' rock.tourist.user_id %}">{{ rock.tourist }}</a></h3>
            </b></div>
            <hr/>
        </h2>

        <h3>
            <div class="card-body">
                {% if rock.image %}
                <div class="image">
                    <img src="{{ rock.image.url }}" width="300" height="300" class="rounded featured-image-list"
                         align="left" vspace="1" hspace="15"
                         alt="Image of {{rock.tourist}}"/>
                </div>
                {% endif %}

                <h3 class="card-title">
                    Перевал: {{ rock.title }}
                </h3>
                <p class="card-text">Широта: {{ rock.latitude }}</p>
                <p class="card-text">Долгота: {{ rock.longitude }}</p>
                <p class="card-text">Высота: {{ rock.height }}</p>
                <p class="card-text">Сезон: {{ rock.level }}</p>
                <p class="card-text">Уровень сложности: {{ rock.level_category }}</p>
                <p class="card-text">Статус проверки: {{ rock.pass_status }}</p>
            </div>
        </h3>
    </div>
</div>

<br/>  <br/>
<h3>
    {% if user.is_superuser or rock.pass_status == 'новый' and user.tourist %}
    <a href="{% url 'rocks:update' rock.id %}"><u>&#128260; Редактировать</u></a>   или
    <a href="{% url 'rocks:delete' rock.id %}"><u> &#128683; Удалить</u></a><br/><br/>
    {% endif %}
    <a href="{% url 'rocks:home' %}">
        <li><i class="fa-solid fa-house"></i> <<<< На главную</li>
    </a>
</h3>
{% endblock content %}

rocks/templates/rocks/update.html
{% extends 'index.html' %}
{% load static %}

{% block title %} Update a pass {% endblock title %}
{% block text %}

<h1> "Изменить первал "{{ rock.title }}"</h1>
{% endblock %}

{% block content %}
{% if rock.pass_status == "новый" and user.tourist or user.is_superuser %}

<div class="features">

    <form method="POST" class="form-parent" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error"> {{ form.non_field_errors }}</div>

        {% for f in form %}
        <p label class="form-label" for={{ f.id_for_lablel }}>
            {{f.label}}: </label> {{f}} </p>
        <div class="form-error">{{f.errors}}</div>
        {% endfor %}

        <input type="submit" value=' "Сохранить" '>

    </form>
</div>
<br/>  <br/>

{% else %}
<h2 style='color:red'>{{ user.tourist }}Вы не можете изменить перевал, не являясь "Туристом"</h2>

{% endif %}
<input type="button" value="Cancel" onclick="history.back()"/>
{% endblock content %}