project/urls.py
from django.contrib import admin
from django.template.context_processors import static
from django.urls import path, include

from project import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('rocks.urls'), name='rocks'),
    path('sign', include('users.urls'), name='sign'),
    ] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rocks/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
app_name: str = 'rocks'
urlpatterns = [
    path('', MainView.as_view(), name='home'),
    path('create/', RockCreateView.as_view(), name='create'),
    path('update/<int:pk>', RockUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', RockDeleteView.as_view(), name='delete'),
    path('rock/<int:pk>', RockView.as_view(), name='rock'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# users/urls.py

from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    # path('', home, name="home"),
    # path("signup/", SignUp.as_view(), name="signup"),
    path("signup/", UserRegister, name="signup"),
    path('user_profile/<int:pk>/', ShowProfilePageView.as_view(), name='user_profile'),
    path('create_user_profile/', CreateProfilePageView.as_view(), name='create_user_profile'),
    path('update_user_profile/<int:pk>/', UpdateProfilePageView.as_view(), name='update_user_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User, Group


class Tourist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, help_text="Турист", primary_key=True)
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(verbose_name='last_name', max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=100)

    # profile_pic = models.ImageField(null=True, blank=True, upload_to="images/profile/")

    def add_to_group(self):
        user = super().User.objects.filter(user=self.user)
        group = Group.objects.filter(name='tourist')
        user.groups.add(group)

    def __str__(self):
        return f" {self.last_name} {self.first_name} {self.middle_name}"

users/views.py
# users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView

from .models import Tourist
from django.contrib.auth.models import User, Group


def UserRegister(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            group = Group.objects.get(name='tourist')
            user.groups.add(group)
            user.save()
            login(request, user)
            return redirect('rocks:home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


class CreateProfilePageView(LoginRequiredMixin, CreateView):
    model = Tourist
    template_name = 'users/create_profile.html'
    permission_required = ['create_profile']
    fields = ["first_name", "middle_name", "last_name", "email", "phone"]

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

    success_url = reverse_lazy('rocks:home')


class UpdateProfilePageView(UpdateView):
    model = Tourist
    permission_required =['update_profile']
    fields = ["first_name", "middle_name", "last_name", "email", "phone"]
    template_name = "users/create_profile.html"
    success_url = reverse_lazy('rocks:home')


class ShowProfilePageView(LoginRequiredMixin, DetailView):
    model = Tourist
    permission_required =['view_user']
    template_name = 'users/user_profile.html'

    def get_context_data(self, *args, **kwargs):
        users = Tourist.objects.all()
        context = super(ShowProfilePageView, self).get_context_data(*args, **kwargs)
        page_user = get_object_or_404(users, pk=self.kwargs['pk'])
        context['page_user'] = page_user
        return context

users/templates/users/create_profile.html
{% extends 'users/main.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<div style="color: #71797E; width: 700px; height: 100px;font-size: 25px; margin: 20px; ">
    <h1>Профиль туриста {{user}}</h1>
</div>
<div class="header-bar">
    <a href="{% url 'rocks:home' %}"> &#8592; На домашнюю</a>
</div>

    <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data"  >
            {% csrf_token %}
            {{form.as_p}}
            <input class="button" type="submit" value="Submit">
            <br/><br/>
            <input type="button" value="Cancel" onclick="history.back()"/>
        </form>
    </div>

{% else %}
<h2>Not "is_authenticated" {{user}}</h2>
<a href="{% url 'users:create_user_profile' %}">Присоединиться к Туристам</a>
{% endif %}

{% endblock content %}

users/templates/users/main.html
<html>
<head >
    <title>Карточка туриста</title>
</head>

<br>
<body style= "background: #ABB2B9;">
{% block content %} {% endblock %}
</body>
</html>

users/templates/users/user_profile.html
{% extends 'index.html' %}
{% block content %}

<div class="header-bar">
    <h1>Профиль туриста {{ user.tourist }}</h1>


</div>

<div class="card-body">
    <h2>
        <p><strong>ФИО:</strong> {{ page_user }}</p>
        <p><strong>Емэйл:</strong> {{ page_user.email }}</p>
        <p><strong>Телефон:</strong> {{ page_user.phone }}</p>
        <p><strong>user.id / tourist.user.id:</strong> {{ user.id }} / {{ tourist.user.id }}</p>
    </h2>
    {% if user.id == tourist.user.id %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'users:update_user_profile' user.id %}"> Редактировать профиль </a>
    </form>
    <hr>
    {% else %}
    <h2 style = 'color:red' >Вы не можете изменить этот профиль, не являясь его владельцем</h2>
    {% endif %}

<!--  <input type="button" value="Cancel" onclick="history.back()"/>-->
</div>
<br/>
        <a href="{% url 'rocks:home' %}">
        <li><i class="fa-solid fa-house"></i> <<<< На главную</li>
    </a>
{% endblock content %}